name: Deploy Documentation 🚀

on:
  push:
    branches:
      - main
      - master
      - update-doc # Ajouté pour permettre de tester la pipeline sur votre branche actuelle

permissions:
  contents: write

jobs:
  deploy:
    name: Build & Publish docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Requis pour récupérer l'historique complet (utile pour les plugins de dates)

      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: '3.x'

      - name: Install MkDocs & Material Theme
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs-material

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          mkdocs gh-deploy --force
